"""Full database schema — SQLAlchemy 2.0, used through an async engine
(see app/database.py). This merges two things built separately earlier
in this project: the bpm-python telemetry receiver's TelemetryEvent
table, and the bpm-screener prototype's Behavioral Database tables —
now in one schema so both live in the same Postgres instance.

Verification status: syntax-checked (py_compile) in this sandbox only.
No network access here to install SQLAlchemy/asyncpg or connect to a
real Postgres instance, so nothing below has been executed against a
live database. Run `alembic upgrade head` (see alembic/) against a real
DATABASE_URL before trusting this in production, and treat
alembic/versions/0001_initial_schema.py as a first draft to review —
it was hand-written to match these models, not autogenerated from a
live DB diff.
"""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Base(DeclarativeBase):
    pass


# ---------------------------------------------------------------------------
# Telemetry (raw receipt log from TradingView — the "sensor" data)
# ---------------------------------------------------------------------------

class TelemetryEvent(Base):
    """One row per confirmed BO or confirmed state transition Pine sent
    via webhook. Event-driven, not one-row-per-candle — gaps are
    expected, not downtime."""

    __tablename__ = "telemetry_events"
    __table_args__ = (UniqueConstraint("event_id", name="uq_telemetry_events_event_id"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    received_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow, nullable=False)

    event_id: Mapped[str] = mapped_column(String(256), nullable=False, index=True)
    schema_version: Mapped[str] = mapped_column(String(32), nullable=False)
    formula_version: Mapped[str] = mapped_column(String(64), nullable=False)
    configuration_id: Mapped[str] = mapped_column(String(128), nullable=False)

    symbol: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    exchange: Mapped[str] = mapped_column(String(64), nullable=False)
    timeframe: Mapped[str] = mapped_column(String(16), nullable=False, index=True)
    bpm_mode: Mapped[str] = mapped_column(String(16), nullable=False, index=True)

    bar_open_time: Mapped[int] = mapped_column(BigInteger, nullable=False)
    bar_close_time: Mapped[int] = mapped_column(BigInteger, nullable=False)

    confirmed_state: Mapped[str] = mapped_column(String(32), nullable=False)
    confirmed_direction: Mapped[str] = mapped_column(String(16), nullable=False)
    bo_status: Mapped[str] = mapped_column(String(32), nullable=False)
    active_bo_price: Mapped[float] = mapped_column(Float, nullable=False)
    mc_status: Mapped[str] = mapped_column(String(32), nullable=False)
    active_mc_price: Mapped[float] = mapped_column(Float, nullable=False)
    pressure_efficiency: Mapped[float] = mapped_column(Float, nullable=False)
    acceptance_status: Mapped[str] = mapped_column(String(32), nullable=False)
    bes_scenario: Mapped[str] = mapped_column(String(64), nullable=False)

    raw_payload: Mapped[str] = mapped_column(Text, nullable=False)


# ---------------------------------------------------------------------------
# Behavioral Database (the research/evidence store)
# ---------------------------------------------------------------------------

class BehavioralSnapshot(Base):
    __tablename__ = "behavioral_snapshots"
    __table_args__ = (
        Index("ix_snapshots_symbol_time", "symbol", "captured_at"),
        Index("ix_snapshots_condition_key", "condition_key"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    captured_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow, nullable=False)

    symbol: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    timeframe: Mapped[str] = mapped_column(String(16), nullable=False)
    bpm_mode: Mapped[str] = mapped_column(String(16), nullable=False)

    confirmed_state: Mapped[str] = mapped_column(String(32), nullable=False)
    confirmed_direction: Mapped[str] = mapped_column(String(16), nullable=False)
    bo_status: Mapped[str] = mapped_column(String(32), nullable=False)
    mc_status: Mapped[str] = mapped_column(String(32), nullable=False)
    pressure_efficiency: Mapped[float] = mapped_column(Float, nullable=False)
    acceptance_status: Mapped[str] = mapped_column(String(32), nullable=False)
    bes_scenario: Mapped[str] = mapped_column(String(64), nullable=False)
    forecast_bias: Mapped[str] = mapped_column(String(32), nullable=True)

    condition_key: Mapped[str] = mapped_column(String(160), nullable=False)
    source_event_id: Mapped[str] = mapped_column(String(256), nullable=True)

    trade_outcomes: Mapped[list["TradeOutcome"]] = relationship(back_populates="snapshot")
    acceptance_events: Mapped[list["AcceptanceEvent"]] = relationship(back_populates="snapshot")
    pressure_bursts: Mapped[list["PressureBurstEvent"]] = relationship(back_populates="snapshot")


class TradeOutcome(Base):
    __tablename__ = "trade_outcomes"
    __table_args__ = (Index("ix_outcomes_snapshot", "snapshot_id"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    snapshot_id: Mapped[int] = mapped_column(ForeignKey("behavioral_snapshots.id"), nullable=False)

    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    exit_price: Mapped[float] = mapped_column(Float, nullable=True)
    r_multiple: Mapped[float] = mapped_column(Float, nullable=True)
    is_win: Mapped[bool] = mapped_column(Boolean, nullable=True)
    hold_bars: Mapped[int] = mapped_column(Integer, nullable=True)
    max_favorable_excursion: Mapped[float] = mapped_column(Float, nullable=True)
    max_adverse_excursion: Mapped[float] = mapped_column(Float, nullable=True)
    closed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)

    snapshot: Mapped["BehavioralSnapshot"] = relationship(back_populates="trade_outcomes")


class BehavioralTransition(Base):
    __tablename__ = "behavioral_transitions"
    __table_args__ = (Index("ix_transitions_symbol_time", "symbol", "occurred_at"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(64), nullable=False)
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow, nullable=False)
    from_state: Mapped[str] = mapped_column(String(32), nullable=False)
    to_state: Mapped[str] = mapped_column(String(32), nullable=False)
    bars_in_prior_state: Mapped[int] = mapped_column(Integer, nullable=True)


class ForecastRecord(Base):
    __tablename__ = "forecast_records"
    __table_args__ = (Index("ix_forecast_symbol_time", "symbol", "issued_at"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(64), nullable=False)
    issued_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow, nullable=False)
    forecast_bias: Mapped[str] = mapped_column(String(32), nullable=False)
    horizon_bars: Mapped[int] = mapped_column(Integer, nullable=False)
    realized_outcome: Mapped[str] = mapped_column(String(32), nullable=True)
    was_correct: Mapped[bool] = mapped_column(Boolean, nullable=True)


class AcceptanceEvent(Base):
    __tablename__ = "acceptance_events"
    __table_args__ = (Index("ix_acceptance_snapshot", "snapshot_id"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    snapshot_id: Mapped[int] = mapped_column(ForeignKey("behavioral_snapshots.id"), nullable=False)
    level_name: Mapped[str] = mapped_column(String(16), nullable=False)
    acceptance_status: Mapped[str] = mapped_column(String(32), nullable=False)
    penetration_depth_atr: Mapped[float] = mapped_column(Float, nullable=True)
    time_held_bars: Mapped[int] = mapped_column(Integer, nullable=True)

    snapshot: Mapped["BehavioralSnapshot"] = relationship(back_populates="acceptance_events")


class PressureBurstEvent(Base):
    __tablename__ = "pressure_burst_events"
    __table_args__ = (Index("ix_pressure_snapshot", "snapshot_id"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    snapshot_id: Mapped[int] = mapped_column(ForeignKey("behavioral_snapshots.id"), nullable=False)
    pressure_efficiency: Mapped[float] = mapped_column(Float, nullable=False)
    magnitude: Mapped[float] = mapped_column(Float, nullable=True)
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow, nullable=False)

    snapshot: Mapped["BehavioralSnapshot"] = relationship(back_populates="pressure_bursts")


class EarningsEventRecord(Base):
    __tablename__ = "earnings_event_records"
    __table_args__ = (Index("ix_earnings_symbol_time", "symbol", "reported_at"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(64), nullable=False)
    reported_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    eps_actual: Mapped[float] = mapped_column(Float, nullable=True)
    eps_estimate: Mapped[float] = mapped_column(Float, nullable=True)
    surprise_pct: Mapped[float] = mapped_column(Float, nullable=True)
    reaction_pct: Mapped[float] = mapped_column(Float, nullable=True)


class NewsCatalystRecord(Base):
    __tablename__ = "news_catalyst_records"
    __table_args__ = (Index("ix_news_symbol_time", "symbol", "published_at"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(64), nullable=False)
    published_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    source: Mapped[str] = mapped_column(String(64), nullable=False)
    headline: Mapped[str] = mapped_column(String(512), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=True)
    relevance: Mapped[float] = mapped_column(Float, nullable=True)
    estimated_behavioral_impact: Mapped[str] = mapped_column(String(16), nullable=True)
    confidence: Mapped[float] = mapped_column(Float, nullable=True)


# ---------------------------------------------------------------------------
# Rankings (persisted output of each ranking run, for /history and audit)
# ---------------------------------------------------------------------------

class RankingRun(Base):
    __tablename__ = "ranking_runs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    run_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow, nullable=False)
    universe_size: Mapped[int] = mapped_column(Integer, nullable=False)

    results: Mapped[list["RankingResult"]] = relationship(back_populates="run")


class RankingResult(Base):
    __tablename__ = "ranking_results"
    __table_args__ = (Index("ix_ranking_results_run_symbol", "run_id", "symbol"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    run_id: Mapped[int] = mapped_column(ForeignKey("ranking_runs.id"), nullable=False)

    rank: Mapped[int] = mapped_column(Integer, nullable=False)
    symbol: Mapped[str] = mapped_column(String(64), nullable=False)
    opportunity_score: Mapped[float] = mapped_column(Float, nullable=False)
    behavior_score: Mapped[float] = mapped_column(Float, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    # Full RankedSymbol, serialized — the normalized columns above exist
    # for fast sorting/filtering; this is the complete explainable record.
    full_result_json: Mapped[str] = mapped_column(Text, nullable=False)

    run: Mapped["RankingRun"] = relationship(back_populates="results")


# ---------------------------------------------------------------------------
# Audit (every rejected/authenticated webhook attempt — security trail)
# ---------------------------------------------------------------------------

class WebhookAuditLog(Base):
    __tablename__ = "webhook_audit_log"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow, nullable=False)
    outcome: Mapped[str] = mapped_column(String(32), nullable=False)  # "accepted"|"duplicate"|"rejected_auth"|"rejected_validation"
    symbol: Mapped[str] = mapped_column(String(64), nullable=True)
    event_id: Mapped[str] = mapped_column(String(256), nullable=True)
    detail: Mapped[str] = mapped_column(Text, nullable=True)
    source_ip: Mapped[str] = mapped_column(String(64), nullable=True)
